### ISSUE TITLE
Cannot access the code on codeocean

### ISSUE THREAD

**Issue by mikochou** [fukexue/POS-BERT#3]
Hi,
Your work is outstanding, but I'm unable to access the code through the provided link. It displays the message, "You don't have permission to access this Capsule. Please contact your administrator for assistance."
Is your code not yet made public? May I know when it will be available for access? Thank you!

**Comment by BBBOYGIRL** [comment]
Hi, I have met the same problem, have you got the code?

**Comment by fukexue** [comment]
all code has been realeased in the paper's github repository

**Comment by Yxlyy** [comment]
> Hi, I'm having the same problem, the paper I'm reading gives a link to the code (codeOcean), but when I click on it, it says You don't have permission to access this Capsule.Please contact your administrator for assistance.., should I try to send an email to the author asking how to access it, or what?
