### ISSUE TITLE
Cannot get the access of the code

### ISSUE THREAD

**Issue by BBBOYGIRL** [fukexue/POS-BERT#4]
Your article is excellent. I want to read the code, but I find that the link is inaccessible. Can you solve this problem? Thank you very much.

**Comment by fukexue** [comment]
all code has been realeased in the paper's github repository

**Comment by BBBOYGIRL** [comment]
When I click the link you have mentioned --  'https://codeocean.com/capsule/5546213/tree', it shows me that 'You don't have permission to access this Capsule. Please contact your administrator for assistance.' How can I get the code?
![link_denied](https://github.com/user-attachments/assets/0baa8528-e206-43a4-b2ae-4b19eca4c655)

**Comment by BBBOYGIRL** [comment]
Thank you very much !
